from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.support.relative_locator import locate_with

options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
driver = webdriver.Chrome(options=options, service=Service(ChromeDriverManager().install()))
driver.get("https://www.instagram.com/")

# Wait till the login fields are available
WebDriverWait(driver, 300).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="loginForm"]/div/div[1]/div/label/input')))
username_input = driver.find_element(By.XPATH, '//*[@id="loginForm"]/div/div[1]/div/label/input')
username_input.send_keys('mahfuzball')

pass_input = driver.find_element(By.XPATH, '//*[@id="loginForm"]/div/div[2]/div/label/input')
pass_input.send_keys('tedmosby')

login_btn = driver.find_element(By.XPATH, '//*[@id="loginForm"]/div/div[3]')
login_btn.click()

auth_code = input('What is the code generated by the authenticator?: ')

auth_input = driver.switch_to.active_element
auth_input.click()
auth_input.send_keys(auth_code)
auth_input.send_keys(Keys.ENTER)


WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.CLASS_NAME, '_aa59')))
not_now = driver.find_element(By.XPATH, '//div[contains(text(), "Not Now")]')
not_now.click()

WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.CLASS_NAME, '_a9_1')))
dont_enable_notification = driver.find_element(By.CLASS_NAME, '_a9_1')
dont_enable_notification.click()

# Maximize window so the search bar with the text "search"  is visible
driver.maximize_window()

# Find the search bar and click on it
search_bar = driver.find_element(By.XPATH, '//span[contains(text(), "Search")]')
search_bar.click()

# A new search bar opens, and it is in focus. So the driver needs to send text in that active element
elem = driver.switch_to.active_element
elem.send_keys('adidas')

# Wait for the search to complete, and adidas page to show
WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.XPATH, '//span[contains(text(), "adidas")]')))

# Now find the result with the name adidas
adidas_page = driver.find_element(By.XPATH, '//span[contains(text(), "adidas")]')
adidas_page.click()

# We're In

# Wait for the adidas page to fully load
WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.XPATH, '//h2[contains(text(), "adidas")]')))
# time.sleep(3.0)

# Click on followers
followers = driver.find_element(By.XPATH, "//a[contains(text(), 'followers')]")
followers.click()

# Wait till the followers window is visible
# It contains the text 'Only Adidas can see all followers'
WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.XPATH, '//span[text()=" can see all followers."]')))

# Find the follow buttons
buttons = driver.find_elements(By.CLASS_NAME, '_acan')
# Now this list contains all the follow buttons, including the one to follow the adidas page, at index 0
# We do not want to click that
# We want to click the follow buttons of the followers, that start from index 1
for i in buttons[1:]:
    i.click()
    # What if you clicked a button that says "Following"?
    if driver.find_element(By.XPATH, "//button[contains(text(), 'Cancel')]"):
        cancel_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Cancel')]")
        cancel_button.click()


# # Find the follow buttons
# follow_buttons = driver.find_elements(By.XPATH, '//div[text()="Follow"]')
# # Loop through the follow buttons and click on them
# for i in follow_buttons:
#     print(i.text)
#     button = locate_with(By.TAG_NAME, "button").to_right_of({By.XPATH: "password"})


# # Find the link with text 'Followed by'
# followers = driver.find_element(By.XPATH, "//span[contains(text(), 'Followed by ')]")
# followers.click()
#
# # Now find the element with text "See all followers" and click
# time.sleep(3.0)
# all_followers = driver.find_element(By.XPATH, "//a[contains(text(), 'See all followers')]")
# all_followers.click()
#
#
# # Now find the element with text "Follow" and click
# # But first switch to active element
#
# mutual_follower = driver.find_element(By.XPATH, "//div[contains(text(), 'Following')]")
# mutual_follower.click()
# time.sleep(3.0)
# cancel_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Cancel')]")
# cancel_button.click()
# time.sleep(3.0)
# new_window = driver.switch_to.active_element
#
# for i in range(0, 5):
#     new_window.send_keys(Keys.END)
#     time.sleep(5.0)
#
# # if driver.find_elements(By.XPATH, '//div[contains(text(), "Follow")]'):
# #     follow_buttons = driver.find_elements(By.XPATH, '//div[contains(text(), "Follow")]')
# #     for button in follow_buttons:
# #         button.click()
# # else:
# #     new_window.send_keys(Keys.ARROW_UP)
#
# followers = driver.find_elements(By.XPATH, "//div[text() = 'Follow')]")
# for i in followers:
#     print(i.text)
#
#
